import type { ProjectState } from '../models/projectState';

// ── Shared helpers ────────────────────────────────────────────────────────────

/** Converts artifact-id (e.g. "my-app") to PascalCase class name (e.g. "MyApp"). */
export function toClassName(artifactId: string): string {
  return artifactId
    .split(/[-_]/)
    .filter(Boolean)
    .map((s) => s.charAt(0).toUpperCase() + s.slice(1))
    .join('');
}

/** Standard warning comment for files NOT generated by the real Initializr (R10). */
const WARNING_COMMENT = `/*
 * Arquivo gerado automaticamente pelo TADS Spring Initializr customizado (versão didática).
 * ATENÇÃO: Este arquivo NÃO é gerado pelo Spring Initializr oficial.
 */`;

// ── Application.java ──────────────────────────────────────────────────────────

export function generateApplication(state: ProjectState, hash: string): string {
  const className = toClassName(state.artifact);
  return `// hash-identificacao: ${hash}
package ${state.packageName};

import org.springframework.boot.SpringApplication;
import org.springframework.boot.autoconfigure.SpringBootApplication;

@SpringBootApplication
public class ${className}Application {

\tpublic static void main(String[] args) {
\t\tSpringApplication.run(${className}Application.class, args);
\t}

}
`;
}

// ── ApplicationTests.java ─────────────────────────────────────────────────────

export function generateApplicationTests(state: ProjectState, hash: string): string {
  const className = toClassName(state.artifact);
  return `// hash-identificacao: ${hash}
package ${state.packageName};

import org.junit.jupiter.api.Test;
import org.springframework.boot.test.context.SpringBootTest;

@SpringBootTest
class ${className}ApplicationTests {

\t@Test
\tvoid contextLoads() {
\t}

}
`;
}

// ── ExemploEntity.java ────────────────────────────────────────────────────────

export function generateEntity(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.model;

import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;

@Entity
@Table(name = "tb_exemplo")
public class ExemploEntity {

\t@Id
\t@GeneratedValue(strategy = GenerationType.IDENTITY)
\tprivate Integer id;

\t@Column(unique = true)
\tprivate String tipo;

\tprivate String mensagem;

\tpublic ExemploEntity() {}

\tpublic ExemploEntity(Integer id, String tipo, String mensagem) {
\t\tthis.id = id;
\t\tthis.tipo = tipo;
\t\tthis.mensagem = mensagem;
\t}

\tpublic Integer getId() { return id; }
\tpublic void setId(Integer id) { this.id = id; }

\tpublic String getTipo() { return tipo; }
\tpublic void setTipo(String tipo) { this.tipo = tipo; }

\tpublic String getMensagem() { return mensagem; }
\tpublic void setMensagem(String mensagem) { this.mensagem = mensagem; }

}
`;
}

// ── ExemploDto.java ───────────────────────────────────────────────────────────

export function generateDto(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.dto;

/*
 * ALTERNATIVA COM RECORD (Java 16+):
 *
 *   public record ExemploDto(Long id, String tipo, String mensagem) {}
 *
 * Com record, o compilador gera automaticamente: construtor canônico, acessores,
 * equals(), hashCode() e toString(). A classe também se torna imutável (campos final).
 * A diferença de uso está no acesso às propriedades:
 *
 *   POJO (esta versão):  objeto.getId()       objeto.getTipo()       objeto.getMensagem()
 *   Record:              objeto.id()          objeto.tipo()          objeto.mensagem()
 */
public class ExemploDto {

\tprivate Integer id;
\tprivate String tipo;
\tprivate String mensagem;

\tpublic ExemploDto() {}

\tpublic ExemploDto(Integer id, String tipo, String mensagem) {
\t\tthis.id = id;
\t\tthis.tipo = tipo;
\t\tthis.mensagem = mensagem;
\t}

\tpublic Integer getId() { return id; }
\tpublic void setId(Integer id) { this.id = id; }

\tpublic String getTipo() { return tipo; }
\tpublic void setTipo(String tipo) { this.tipo = tipo; }

\tpublic String getMensagem() { return mensagem; }
\tpublic void setMensagem(String mensagem) { this.mensagem = mensagem; }

}
`;
}

// ── ExemploRepository.java ────────────────────────────────────────────────────

export function generateRepository(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.repository;

import ${pkg}.model.ExemploEntity;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.NativeQuery;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.Optional;

public interface ExemploRepository extends JpaRepository<ExemploEntity, Integer> {

\t// Exemplo de Derived Query: Spring Data gera o SQL automaticamente a partir do nome do método
\t// formado por "findBy" + nome do campo "tipo" presente na classe ExemploEntity
\tOptional<ExemploEntity> findByTipo(String tipo);

\t// Exemplo de uso do JPQL com @Query - Usar o nome da classe Entity
\t@Query("SELECT e FROM ExemploEntity e WHERE e.tipo = :tipo")
\tOptional<ExemploEntity> findExemploJpql(@Param("tipo") String tipo);

\t// Exemplo de uso de SQL Nativo com @NativeQuery - Usar o nome da tabela gerada no banco de dados
\t@NativeQuery("SELECT * FROM tb_exemplo WHERE tipo = :tipo") // Ou @Query acima com nativeQuery = true
\tOptional<ExemploEntity> findExemploSqlNativo(@Param("tipo") String tipo);

}
`;
}

// ── ExemploService.java ───────────────────────────────────────────────────────

export function generateService(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  const hasJpa = state.dependencies.includes('data-jpa');

  if (hasJpa) {
    return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.service;

import ${pkg}.dto.ExemploDto;
import ${pkg}.model.ExemploEntity;
import ${pkg}.repository.ExemploRepository;
import org.springframework.stereotype.Service;

import java.util.ArrayList;
import java.util.List;
import java.util.Optional;

@Service
public class ExemploService {

\tprivate final ExemploRepository repository;

\t// Construtor usado para injeção de dependência do bean ExemploRepository
\t// Substitui a necessidade de criar manualmente uma instância do repository, o Spring faz isso automaticamente
\t// Não usar o @Autowired (injeção por campo) em projetos modernos
\tpublic ExemploService(ExemploRepository repository) {
\t\tthis.repository = repository;
\t}

\tpublic List<ExemploDto> findAll() {
\t\tList<ExemploDto> resultado = new ArrayList<>();
\t\tfor (ExemploEntity entity : repository.findAll()) {
\t\t\tresultado.add(toDto(entity));
\t\t}
\t\treturn resultado;

\t\t// *** Alternativa funcional:
\t\t// return repository.findAll().stream().map(this::toDto).toList();
\t}

\tpublic Optional<ExemploDto> findByTipo(String tipo) {
\t\tOptional<ExemploEntity> optEntity = repository.findByTipo(tipo);
\t\tif (optEntity.isEmpty()) {
\t\t\treturn Optional.empty();
\t\t}
\t\tExemploEntity entity = optEntity.get();
\t\tExemploDto dto = toDto(entity);
\t\treturn Optional.of(dto);

\t\t// *** Alternativa funcional:
\t\t// return repository.findByTipo(tipo).map(this::toDto);
\t}

\tpublic ExemploDto addNew(ExemploDto dto) {
\t\tExemploEntity entity = toEntity(dto);
\t\tExemploEntity salvo = repository.save(entity);
\t\treturn toDto(salvo);
\t}

\t // ##### FUNÇÕES MAPPERS (Mapeamento Dto para Entity e vice-versa)

\tprivate ExemploDto toDto(ExemploEntity entity) {
\t\treturn new ExemploDto(entity.getId(), entity.getTipo(), entity.getMensagem());
\t}

\tprivate ExemploEntity toEntity(ExemploDto dto) {
\t\tExemploEntity entity = new ExemploEntity();
\t\tentity.setTipo(dto.getTipo());
\t\tentity.setMensagem(dto.getMensagem());
\t\treturn entity;
\t}

}
`;
  }

  // R4: in-memory list
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.service;

import ${pkg}.dto.ExemploDto;
import org.springframework.stereotype.Service;

import java.util.List;
import java.util.Map;
import java.util.Optional;
import java.util.concurrent.ConcurrentHashMap;
import java.util.concurrent.atomic.AtomicInteger;

@Service
public class ExemploService {

\t// tipo é chave única no formato String: cada objeto no map (valor) é identificado por seu tipo único
\tprivate final Map<String, ExemploDto> dados = new ConcurrentHashMap<>();
\tprivate final AtomicInteger counter = new AtomicInteger(0);

\tpublic ExemploService() {
\t\tdados.put("hello", new ExemploDto(counter.incrementAndGet(), "hello", "Hello Spring Boot"));
\t\tdados.put("exemplo", new ExemploDto(counter.incrementAndGet(), "exemplo", "Exemplo de dados"));
\t\tdados.put("teste", new ExemploDto(counter.incrementAndGet(), "teste", "Teste"));
\t\tdados.put("demo", new ExemploDto(counter.incrementAndGet(), "demo", "Dados da aplicação de demonstração"));
\t}

\tpublic List<ExemploDto> findAll() {
\t\treturn List.copyOf(dados.values());
\t}

\tpublic Optional<ExemploDto> findByTipo(String tipo) {
\t\treturn Optional.ofNullable(dados.get(tipo));
\t}

\tpublic ExemploDto addNew(ExemploDto dto) {
\t\tExemploDto novo = new ExemploDto(counter.incrementAndGet(), dto.getTipo(), dto.getMensagem());
\t\tdados.put(novo.getTipo(), novo);
\t\treturn novo;
\t}

}
`;
}

// ── ExemploRestController.java ────────────────────────────────────────────────

export function generateRestController(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.controller;

import ${pkg}.dto.ExemploDto;
import ${pkg}.service.ExemploService;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RestController;

import java.util.List;
import java.util.Optional;

@RestController
@RequestMapping("/api/exemplos")
public class ExemploRestController {

\tprivate final ExemploService service;

\t// Construtor usado para injeção de dependência do bean ExemploService
\t// Substitui a necessidade de criar manualmente uma instância do service, o Spring faz isso automaticamente
\t// Não usar o @Autowired (injeção por campo) em projetos modernos
\tpublic ExemploRestController(ExemploService service) {
\t\tthis.service = service;
\t}

\t@GetMapping
\tpublic List<ExemploDto> listarTodos() {
\t\treturn service.findAll();
\t}

\t@GetMapping("/{tipo}")
\tpublic ResponseEntity<ExemploDto> buscarPorTipo(@PathVariable String tipo) {
\t\tOptional<ExemploDto> optDado = service.findByTipo(tipo);
\t\tif (optDado.isEmpty()) {
\t\t\treturn ResponseEntity.notFound().build();
\t\t}
\t\tExemploDto dados = optDado.get();  
\t\treturn ResponseEntity.ok(dados);

\t\t// *** Alternativa funcional:
\t\t// return service.findByTipo(tipo)
\t\t//\t\t.map(ResponseEntity::ok)
\t\t//\t\t.orElse(ResponseEntity.notFound().build());
\t}

\t@PostMapping
\tpublic ResponseEntity<ExemploDto> adicionar(@RequestBody ExemploDto dto) {
\t\treturn ResponseEntity.ok(service.addNew(dto));
\t}

}
`;
}

// ── ExemploController.java (MVC / Thymeleaf) ──────────────────────────────────

export function generateMvcController(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.controller;

import ${pkg}.dto.ExemploDto;
import ${pkg}.service.ExemploService;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PostMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.servlet.mvc.support.RedirectAttributes;

@Controller
@RequestMapping("/exemplos")
public class ExemploController {

\tprivate final ExemploService service;

\tpublic ExemploController(ExemploService service) {
\t\tthis.service = service;
\t}

\t@GetMapping
\tpublic String listar(Model model) {
\t\tmodel.addAttribute("exemplos", service.findAll());
\t\treturn "exemplos/lista";
\t}

\t@GetMapping("/novo")
\tpublic String mostrarFormNovo(Model model) {
\t\tmodel.addAttribute("exemplo", new ExemploDto(null, "", ""));
\t\treturn "exemplos/form";
\t}

\t@PostMapping
\tpublic String salvarNovo(@ModelAttribute ExemploDto dto, RedirectAttributes redirectAttributes) {
\t\tservice.addNew(dto);
\t\tredirectAttributes.addFlashAttribute("mensagemSucesso", "Registro adicionado com sucesso!");
\t\treturn "redirect:/exemplos";
\t}

}
`;
}

// ── SecurityConfig.java ───────────────────────────────────────────────────────

export function generateSecurityConfig(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.config;

import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;
import org.springframework.security.config.annotation.web.builders.HttpSecurity;
import org.springframework.security.config.annotation.web.configuration.EnableWebSecurity;
import org.springframework.security.web.SecurityFilterChain;
import org.springframework.web.cors.CorsConfiguration;
import org.springframework.web.cors.CorsConfigurationSource;
import org.springframework.web.cors.UrlBasedCorsConfigurationSource;

import java.util.List;

// ATENÇÃO: Esta configuração permite acesso sem autenticação a todos os endpoints.
// Ajuste conforme as necessidades de segurança do seu projeto em produção.
@Configuration
@EnableWebSecurity
public class SecurityConfig {

\t@Bean
\tpublic SecurityFilterChain filterChain(HttpSecurity http) throws Exception {
\t\thttp
\t\t\t\t.authorizeHttpRequests(auth -> auth.anyRequest().permitAll())
\t\t\t\t.cors(cors -> cors.configurationSource(corsConfigurationSource()))
\t\t\t\t.csrf(csrf -> csrf.disable());
\t\treturn http.build();
\t}

\t@Bean
\tpublic CorsConfigurationSource corsConfigurationSource() {
\t\tCorsConfiguration config = new CorsConfiguration();
\t\tconfig.setAllowedOriginPatterns(List.of("*"));
\t\tconfig.setAllowedMethods(List.of("GET", "POST", "PUT", "DELETE", "OPTIONS"));
\t\tconfig.setAllowedHeaders(List.of("*"));
\t\tUrlBasedCorsConfigurationSource source = new UrlBasedCorsConfigurationSource();
\t\tsource.registerCorsConfiguration("/**", config);
\t\treturn source;
\t}

}
`;
}

// ── OpenApiConfig.java ────────────────────────────────────────────────────────

export function generateOpenApiConfig(state: ProjectState, hash: string): string {
  const pkg = state.packageName;
  return `// hash-identificacao: ${hash}
${WARNING_COMMENT}
package ${pkg}.config;

import io.swagger.v3.oas.models.OpenAPI;
import io.swagger.v3.oas.models.info.Info;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Configuration;

@Configuration
public class OpenApiConfig {

\t@Bean
\tpublic OpenAPI customOpenAPI() {
\t\treturn new OpenAPI()
\t\t\t\t.info(new Info()
\t\t\t\t\t\t.title("${state.name} API")
\t\t\t\t\t\t.description("${state.description}")
\t\t\t\t\t\t.version("1.0.0"));
\t}

}
`;
}
